backend:
  name: github
  repo: muftiraheemuddinsahib/mufti.sb-site # IMPORTANT: Change this line!
  branch: main
  auth_type: implicit
  app_id: Ov23liQbbbOFtcwcFrdk # IMPORTANT: Change this line!

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
